export const mockArticles = [
    {
        article_id: "mock-001",
        title: "Global markets remain steady as technology stocks rise",
        description: "Technology companies helped stabilize global markets after a week of economic uncertainty.",
        content: "Technology companies helped stabilize global markets after a week of economic uncertainty.",
        link: "https://example.com/global-markets",
        image_url: "https://images.unsplash.com/photo-1520607162513-77705c0f0d4a",
        pubDate: "2026-05-17 10:00:00",
        pubDateTZ: "UTC",
        source_name: "Financial Daily",
        source_url: "https://example.com",
        source_icon: null,
        category: ["business"],
        country: ["united states"],
        language: "english",
        creator: ["News Desk"],
        keywords: ["markets", "technology", "stocks"]
    },
    {
        article_id: "mock-002",
        title: "New advances in artificial intelligence reshape digital products",
        description: "Companies are integrating AI tools into everyday platforms to improve productivity and user experience.",
        content: "Companies are integrating AI tools into everyday platforms to improve productivity and user experience.",
        link: "https://example.com/ai-products",
        image_url: "https://images.unsplash.com/photo-1677442136019-21780ecad995",
        pubDate: "2026-05-17 12:30:00",
        pubDateTZ: "UTC",
        source_name: "Tech Review",
        source_url: "https://example.com",
        source_icon: null,
        category: ["technology"],
        country: ["united states"],
        language: "english",
        creator: ["Technology Desk"],
        keywords: ["artificial intelligence", "digital products", "software"]
    },
    {
        article_id: "mock-003",
        title: "Climate researchers publish new report on urban sustainability",
        description: "The report highlights the importance of sustainable transport, green infrastructure and energy efficiency.",
        content: "The report highlights the importance of sustainable transport, green infrastructure and energy efficiency.",
        link: "https://example.com/climate-report",
        image_url: "https://images.unsplash.com/photo-1494526585095-c41746248156",
        pubDate: "2026-05-16 18:15:00",
        pubDateTZ: "UTC",
        source_name: "Science World",
        source_url: "https://example.com",
        source_icon: null,
        category: ["environment"],
        country: ["united states"],
        language: "english",
        creator: ["Science Desk"],
        keywords: ["climate", "sustainability", "urban planning"]
    }
];